import { useEffect, useState } from 'react';
import { ArrowLeft, ImagePlus, PackagePlus, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { adjustProductStock, createProduct, deleteProduct, editProduct, getProducts, toggleProduct } from './api';

const emptyForm = { productCode: '', name: '', slug: '', description: '', imageUrl: '', charmCount: 1, stock: 0, lowStockThreshold: 3, stockManaged: false, active: true, sortOrder: 0 };

function ProductManagement({ token, onBack }) {
  const [products, setProducts] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(null); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); try { const result = await getProducts(token, query); setProducts(result.data || []); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  function open(product = null) { setModal({ product, form: product ? { ...emptyForm, ...product, imageUrl: product.image || '' } : { ...emptyForm }, file: null }); }
  function update(name, value) { setModal((current) => ({ ...current, form: { ...current.form, [name]: value } })); }
  async function save(event) { event.preventDefault(); setSaving(true); const data = new FormData(); Object.entries(modal.form).forEach(([key, value]) => data.append(key, String(value))); if (modal.file) data.append('image', modal.file); try { if (modal.product) await editProduct(token, modal.product._id, data); else await createProduct(token, data); setModal(null); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  async function remove(product) { if (!window.confirm(`Xóa sản phẩm “${product.name}”?`)) return; try { await deleteProduct(token, product._id); await load(); } catch (e) { setError(e.message); } }
  async function adjust(product) { try { await adjustProductStock(token, product._id, 1); await load(); } catch (e) { setError(e.message); } }
  const low = products.filter((product) => product.stockManaged && product.stock <= product.lowStockThreshold).length;
  return <div className="admin-shell"><header className="admin-top"><div className="brand">CHẠM Ý <small>PRODUCTS & INVENTORY</small></div><button className="logout" onClick={onBack}><ArrowLeft size={14} /> Đơn hàng</button></header><main className="admin-main products-page"><div className="admin-heading"><div><p className="eyebrow">KHO SẢN PHẨM</p><h1>Sản phẩm có sẵn.</h1></div><button className="export" onClick={() => open()}><Plus size={16} /> Thêm sản phẩm</button></div><div className="product-stats"><article><span>Tổng sản phẩm</span><strong>{products.length}</strong></article><article><span>Đang bán</span><strong>{products.filter((product) => product.active).length}</strong></article><article><span>Sắp hết hàng</span><strong>{low}</strong></article></div><form className="product-toolbar" onSubmit={(event) => { event.preventDefault(); load(); }}><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tên hoặc mã sản phẩm" /><button type="submit">Tìm kiếm</button><button type="button" onClick={load}><RefreshCw size={15} /> Làm mới</button></form>{error && <div className="error">{error}</div>}<div className="product-admin-grid">{loading ? <div className="product-empty">Đang tải sản phẩm...</div> : products.length ? products.map((product) => <article className="product-admin-card" key={product._id}><div className="product-admin-image"><img src={product.image} alt={product.name} /></div><div className="product-admin-copy"><div className="product-admin-title"><div><small>{product.productCode}</small><h2>{product.name}</h2></div><span className={`product-status ${product.active ? 'is-active' : ''}`}>{product.active ? 'Đang bán' : 'Đã ẩn'}</span></div><p>{product.description || 'Chưa có mô tả sản phẩm.'}</p><div className="product-admin-meta"><span>{product.charmCount} charm · Giá theo bảng chung</span><strong>{product.stockManaged ? `${product.stock} sản phẩm` : 'Chưa bật tồn kho'}</strong></div><div className="product-admin-actions"><button type="button" onClick={() => open(product)}><Pencil size={14} /> Sửa</button><button type="button" onClick={() => adjust(product)}><PackagePlus size={14} /> Nhập +1</button><button type="button" onClick={() => toggleProduct(token, product._id, !product.active).then(load)}>{product.active ? 'Ẩn sản phẩm' : 'Hiện sản phẩm'}</button><button type="button" onClick={() => remove(product)}><Trash2 size={14} /> Xóa</button></div></div></article>) : <div className="product-empty">Chưa có sản phẩm.</div>}</div></main>{modal && <ProductForm modal={modal} setModal={setModal} update={update} save={save} saving={saving} close={() => setModal(null)} />}</div>;
}

function ProductForm({ modal, setModal, update, save, saving, close }) { const { form, product } = modal; return <div className="admin-modal-backdrop" onClick={close}><form className="product-form-modal" onSubmit={save} onClick={(event) => event.stopPropagation()}><button className="reject-modal-close" type="button" onClick={close}><X size={18} /></button><p className="eyebrow">{product ? 'CHỈNH SỬA SẢN PHẨM' : 'SẢN PHẨM MỚI'}</p><h2>{product ? form.name : 'Thêm sản phẩm có sẵn'}</h2><div className="product-form-grid"><label>Mã sản phẩm<input required value={form.productCode} disabled={Boolean(product)} onChange={(event) => update('productCode', event.target.value)} /></label><label>Tên sản phẩm<input required value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label>Slug<input required value={form.slug} onChange={(event) => update('slug', event.target.value)} /></label><label>Số charm<input type="number" min="1" max="3" value={form.charmCount} onChange={(event) => update('charmCount', event.target.value)} /></label><label>Tồn kho<input type="number" min="0" value={form.stock} onChange={(event) => update('stock', event.target.value)} /></label><label>Ngưỡng cảnh báo<input type="number" min="0" value={form.lowStockThreshold} onChange={(event) => update('lowStockThreshold', event.target.value)} /></label><label className="wide">Mô tả<textarea value={form.description} onChange={(event) => update('description', event.target.value)} /></label><label className="wide upload-product"><ImagePlus size={16} /> Ảnh sản phẩm<input type="file" accept="image/*" onChange={(event) => setModal((current) => ({ ...current, file: event.target.files?.[0] || null }))} />{modal.file?.name || form.imageUrl || 'Chọn ảnh hoặc dán URL bên dưới'}</label><label className="wide">URL ảnh<input value={form.imageUrl} onChange={(event) => update('imageUrl', event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={form.stockManaged} onChange={(event) => update('stockManaged', event.target.checked)} /> Bật quản lý tồn kho</label><label className="checkbox-field"><input type="checkbox" checked={form.active} onChange={(event) => update('active', event.target.checked)} /> Hiển thị trên cửa hàng</label></div><div className="product-form-actions"><button type="button" onClick={close}>Hủy</button><button className="export" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu sản phẩm'}</button></div></form></div>; }

export default ProductManagement;
