import { Router } from 'express';
import { adminLogin, refreshAdminToken } from '../controllers/auth.controller.js';
import { dashboard, exportOrders, getOrder, listOrders, updateStatus } from '../controllers/admin-order.controller.js';
import { requireAdmin } from '../middleware/auth.middleware.js';
import { createProduct, deleteProduct, getAdminProduct, listAdminProducts, toggleProduct, updateProduct, updateProductStock } from '../controllers/product.controller.js';
import { upload } from '../middleware/upload.middleware.js';

const router = Router();
router.post('/login', adminLogin);
router.post('/refresh', refreshAdminToken);
router.use(requireAdmin);
router.get('/dashboard', dashboard);
router.get('/orders', listOrders);
router.get('/orders/export', exportOrders);
router.get('/orders/:id', getOrder);
router.patch('/orders/:id/status', updateStatus);
router.get('/products', listAdminProducts);
router.get('/products/:id', getAdminProduct);
router.post('/products', upload.fields([{ name: 'image', maxCount: 1 }]), createProduct);
router.patch('/products/:id', upload.fields([{ name: 'image', maxCount: 1 }]), updateProduct);
router.patch('/products/:id/stock', updateProductStock);
router.patch('/products/:id/active', toggleProduct);
router.delete('/products/:id', deleteProduct);
export default router;
