import { useState } from 'react';
import { lookupOrder } from '../lib/api';
import { money } from '../lib/formatters';

function Orders() {
  const [phone, setPhone] = useState(''); const [orders, setOrders] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { setOrders(await lookupOrder(phone)); } catch (e) { setOrders([]); setError(e.message); } finally { setLoading(false); } }
  return <main className="page orders-page"><div className="page-intro"><p className="eyebrow">ĐƠN HÀNG CỦA TÔI</p><h1>Tra lại đơn<br /><em>của bạn.</em></h1><p>Nhập số điện thoại đã dùng khi đặt hàng để xem tất cả đơn của bạn.</p></div><form className="orders-lookup" onSubmit={submit}><input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="SỐ ĐIỆN THOẠI" required /><button className="primary" disabled={loading}>{loading ? 'Đang tìm...' : 'Xem đơn hàng'}</button></form>{error && <p className="form-error">{error}</p>}{orders.map((order) => <article className="order-result" key={order._id}><div className="order-result-head"><div><p className="eyebrow">{order.orderCode}</p><h2>{new Date(order.createdAt).toLocaleString('vi-VN')}</h2></div><span className={`status-pill ${order.status.toLowerCase()}`}>{order.status === 'PENDING' ? 'Chưa hoàn thành' : order.status === 'REJECTED' ? 'Từ chối xử lý' : 'Đã hoàn thành'}</span></div>{order.rejectionReason && <p className="order-rejection-reason"><b>Lý do từ chối:</b> {order.rejectionReason}</p>}{order.items.map((item) => <div className="order-result-item" key={`${order._id}-${item.productId}`}><img src={item.productImage} alt={item.productName} /><div><b>{item.productName}</b><span>{item.quantity} × {money(item.unitPrice)}</span></div><strong>{money(item.subtotal)}</strong></div>)}<div className="order-result-total"><span>Tổng cộng</span><strong>{money(order.totalAmount)}</strong></div>{order.previewImage?.url && <img className="order-result-preview" src={order.previewImage.url} alt="Preview đơn hàng" />}</article>)}</main>;
}
export default Orders;
